### ISSUE TITLE
Python dependencies under Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by floe-de** [chadparry/kodi-plugin.program.remote.control.browser#7]
Hi,

I have tried to get the Remote Control Browser Addon to work under Ubuntu 20.04. Installed is version 1.6.0 from your repository under Kodi 18.9.

Launching the YouTube, Netflix links does not work and a note about an error is displayed in the log file. How can I find the log file?

The recommendation to install the additional packages does not work either because the packages are not available in Ubuntu 20.04.

sudo apt-get install -y python-pip python-psutil python-alsaaudio python-pylirc python-pil unclutter & sudo pip install pulsectl

For python-pip there is the package python3-pip the others I haven't found yet. The question is also if they will work because you are using Python 2 and Ubuntu is on Python3, just like Kodi in version 19. Are there any plans to migrate the addon to Python 3 or is there another solution / recommendation to get your addon running on Ubuntu 20.04?

I would really appreciate an answer, happy holidays.

**Comment by floe-de** [comment]
This is the log entry from .kodi/temp/kodi.log

2020-12-22 08:54:33.134 T:140475025585920 WARNING: Missing Python package: psutil
2020-12-22 08:54:33.134 T:140475025585920 WARNING: Missing Python package: pylirc2
2020-12-22 08:54:33.135 T:140475025585920 WARNING: Missing Python package: pyalsaaudio
2020-12-22 08:54:33.136 T:140475025585920 WARNING: Missing Python package: pulsectl
2020-12-22 08:54:36.895 T:140476701072064   ERROR: Control 55 in window 10001 has been asked to focus, but it can't
2020-12-22 08:54:52.679 T:140476567381760   ERROR: Previous line repeats 2 times.
2020-12-22 08:54:52.679 T:140476567381760   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: [Errno 13] Permission denied
                                            Traceback (most recent call last):
                                              File "/home/icke/.kodi/addons/plugin.program.remote.control.browser/plugin.py", line 870, in <module>
                                                main()
                                              File "/home/icke/.kodi/addons/plugin.program.remote.control.browser/plugin.py", line 866, in main
                                                handler(args)
                                              File "/home/icke/.kodi/addons/plugin.program.remote.control.browser/plugin.py", line 856, in <lambda>
                                                getBookmarkId(args)),
                                              File "/home/icke/.kodi/addons/plugin.program.remote.control.browser/plugin.py", line 678, in launchBookmark
                                                self.launchUrl(url, lircConfig)
                                              File "/home/icke/.kodi/addons/plugin.program.remote.control.browser/plugin.py", line 725, in launchUrl
                                                alsaControl)
                                              File "/home/icke/.kodi/addons/plugin.program.remote.control.browser/plugin.py", line 780, in spawnBrowser
                                                stderr=subprocess.PIPE)
                                              File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
                                                errread, errwrite)
                                              File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
                                                raise child_exception
                                            OSError: [Errno 13] Permission denied
                                            -->End of Python script error report<--

**Comment by chadparry** [comment]
I've finally upgraded the add-on to support Python 3 and Kodi 19. Upgrade to v2.0.0. You'll have to run this command to install an updated version of the `pylirc2` dependency:
```
pip3 install ~/.kodi/addons/plugin.program.remote.control.browser/resources/lib/pylirc
```
